spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stm?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 780013490

  thymeleaf:
    cache: false



mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 18080

